# Generated by Django 3.0.7 on 2020-07-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='List',
        ),
    ]
